import { Signal } from './types';

export const seedSignals: Signal[] = [
  {
    id: 'sig-001',
    title: 'Senior Frontend Engineer (Remote / Uzbekistan)',
    summary: 'Next.js 15, TypeScript va Tailwind CSS boʻyicha chuqur bilimga ega dasturchi qidirilmoqda. Xalqaro loyiha, moslashuvchan grafik.',
    url: 'https://jobs.example.com/senior-frontend',
    sourceType: 'telegram',
    sourceLabel: '@dev_jobs_uz',
    collection: 'jobs',
    tags: ['remote', 'nextjs', 'typescript', 'frontend'],
    status: 'new',
    note: 'Rezyume va portfolio tayyorlab, juma kuniga qadar yuborish lozim.',
    deadline: '2026-09-25',
    createdAt: '2026-09-20T08:30:00Z',
  },
  {
    id: 'sig-002',
    title: 'Distributed Systems with Go — Advanced Course',
    summary: 'Comprehensive hands-on course covering Raft consensus, gRPC streaming, and distributed key-value storage architectures.',
    url: 'https://courses.example.com/distributed-go',
    sourceType: 'web',
    sourceLabel: 'golangweekly.com',
    collection: 'courses',
    tags: ['golang', 'distributed-systems', 'backend'],
    status: 'new',
    note: 'Check the syllabus and practice chapter 1 over the weekend.',
    createdAt: '2026-09-19T14:15:00Z',
  },
  {
    id: 'sig-003',
    title: 'Toshkent markazida shinam kovorking va ofis ijarasi',
    summary: 'Oybek metrosi yaqinida 24/7 ishlaydigan zamonaviy kovorking joylari, tezyurar internet va qahva zonasi mavjud.',
    url: 'https://t.me/coworking_tashkent/452',
    sourceType: 'telegram',
    sourceLabel: '@coworking_tashkent',
    collection: 'housing',
    tags: ['toshkent', 'ofis', 'kovorking'],
    status: 'read',
    note: 'Joyni borib koʻrish va oylik tariflarni solishtirish kerak.',
    deadline: '2026-09-24',
    createdAt: '2026-09-19T11:00:00Z',
  },
  {
    id: 'sig-004',
    title: 'Full-stack Next.js + PostgreSQL MVP loyihasi',
    summary: 'Elektron tijorat platformasi uchun 3 haftalik freelance buyurtma. Admin panel va toʻlov tizimlari integratsiyasi.',
    url: 'https://freelance.example.com/project/8812',
    sourceType: 'web',
    sourceLabel: 'freelancehunt.com',
    collection: 'freelance',
    tags: ['freelance', 'nextjs', 'postgres', 'ecommerce'],
    status: 'new',
    note: 'Texnik topshiriqni baholash va taklif yuborish.',
    deadline: '2026-09-22',
    createdAt: '2026-09-18T16:45:00Z',
  },
  {
    id: 'sig-005',
    title: 'Biome: Fast Formatter and Linter for Web Projects',
    summary: 'Rust-based toolchain that unifies linting, formatting, and import sorting in a single binary. 35x faster than Prettier.',
    url: 'https://biomejs.dev',
    sourceType: 'web',
    sourceLabel: 'github.com/biomejs',
    collection: 'tools',
    tags: ['developer-tools', 'rust', 'typescript', 'dx'],
    status: 'done',
    note: 'Benchmarked on a side-project: formatting time dropped from 4.2s to 110ms.',
    createdAt: '2026-09-18T09:20:00Z',
  },
  {
    id: 'sig-006',
    title: 'PostgreSQL Indexing: The Complete Visual Guide',
    summary: 'Deep dive into B-tree, BRIN, GIN, and GiST indexes with query plan analysis and memory tuning benchmarks.',
    url: 'https://use-the-index-luke.com',
    sourceType: 'web',
    sourceLabel: 'database-internals.blog',
    collection: 'courses',
    tags: ['database', 'postgres', 'performance'],
    status: 'read',
    note: 'Useful section on partial indexes for multi-tenant tables.',
    createdAt: '2026-09-17T18:00:00Z',
  },
  {
    id: 'sig-007',
    title: 'React 19 Server Actions va Optimistic UI amaliyoti',
    summary: 'Yangi React 19 xususiyatlari: useActionState, useOptimistic va Server Actions boʻyicha tahliliy maqola va kod namunalari.',
    url: 'https://t.me/frontend_uz/1209',
    sourceType: 'telegram',
    sourceLabel: '@frontend_uz',
    collection: 'courses',
    tags: ['react19', 'server-actions', 'optimistic-ui'],
    status: 'new',
    note: 'Kepio kutubxona formasida useActionState tatbiq etish.',
    createdAt: '2026-09-17T13:10:00Z',
  },
  {
    id: 'sig-008',
    title: 'UI/UX Dizayn Tizimi — Figma Tokenlaridan Kodga',
    summary: 'Design tokens arxitekturasi: ranglar, tipografiya va boʻshliqlar tizimini kod bilan sinxronlashtirish boʻyicha qoʻllanma.',
    url: 'https://t.me/design_craft_uz/310',
    sourceType: 'telegram',
    sourceLabel: '@design_craft_uz',
    collection: 'tools',
    tags: ['figma', 'design-tokens', 'css-vars'],
    status: 'done',
    createdAt: '2026-09-16T15:30:00Z',
  },
  {
    id: 'sig-009',
    title: 'Lead Product Designer (Fintech / Tashkent)',
    summary: 'Bank mobil ilovalari va veb-ekotizimini takomillashtirish uchun tajribali mahsulot dizayneri talab etiladi.',
    url: 'https://jobs.example.com/fintech-lead-designer',
    sourceType: 'telegram',
    sourceLabel: '@tashkent_tech_jobs',
    collection: 'jobs',
    tags: ['ux-ui', 'fintech', 'tashkent', 'lead'],
    status: 'archived',
    createdAt: '2026-09-16T10:05:00Z',
  },
  {
    id: 'sig-010',
    title: 'Tailwind CSS v4 Architecture & CSS-First Engine',
    summary: 'Detailed architectural overview of Tailwind v4 lightningcss integration, theme variables, and zero-config build system.',
    url: 'https://tailwindcss.com/blog/tailwindcss-v4-alpha',
    sourceType: 'web',
    sourceLabel: 'tailwindcss.com',
    collection: 'tools',
    tags: ['css', 'tailwind', 'frontend', 'build-tools'],
    status: 'read',
    createdAt: '2026-09-15T20:00:00Z',
  },
  {
    id: 'sig-011',
    title: 'Telegram Bot API orqali bildirishnomalar yuborish tizimi',
    summary: 'Node.js va Telegraf yordamida veb-ilova hodisalarini Telegram kanallarga va guruhlarga uzatuvchi mikroxizmat.',
    url: 'https://github.com/example/telegram-notifier-microservice',
    sourceType: 'telegram',
    sourceLabel: '@backend_pro_uz',
    collection: 'tools',
    tags: ['nodejs', 'telegram-bot', 'microservice'],
    status: 'new',
    note: 'Kepio Phase 2 da backendga ulash uchun arxitekturani koʻrib chiqish.',
    createdAt: '2026-09-15T14:40:00Z',
  },
  {
    id: 'sig-012',
    title: 'Yunusobodda 3 xonali xonadon ijarasi',
    summary: 'Metro yaqinida, yangi taʼmirlangan, barcha maishiy texnikalari bilan toʻliq jihozlangan xonadon.',
    url: 'https://olx.uz/d/obyavlenie/yunusobod-3-xona-ijara',
    sourceType: 'web',
    sourceLabel: 'olx.uz',
    collection: 'housing',
    tags: ['toshkent', 'ijara', 'yunusobod'],
    status: 'archived',
    createdAt: '2026-09-14T17:15:00Z',
  },
  {
    id: 'sig-013',
    title: 'Building Resilient Offline-First Web Applications with IndexedDB',
    summary: 'Patterns for synchronizing local browser storage with cloud databases, conflict resolution, and CRDT data types.',
    url: 'https://offlinefirst.org/deep-dive',
    sourceType: 'web',
    sourceLabel: 'web.dev',
    collection: 'courses',
    tags: ['offline-first', 'indexeddb', 'crdt', 'architecture'],
    status: 'new',
    createdAt: '2026-09-14T11:20:00Z',
  },
  {
    id: 'sig-014',
    title: 'Mobile App Redesign for Logistics Startup (Flutter/Figma)',
    summary: 'Short-term freelance contract to revamp the courier delivery mobile interface and design high-contrast night mode.',
    url: 'https://upwork.com/jobs/~01abcde990',
    sourceType: 'web',
    sourceLabel: 'upwork.com',
    collection: 'freelance',
    tags: ['freelance', 'flutter', 'ui-redesign', 'mobile'],
    status: 'done',
    deadline: '2026-09-18',
    createdAt: '2026-09-13T19:50:00Z',
  },
  {
    id: 'sig-015',
    title: 'Oʻzbek tilidagi qonunlar va meʼyoriy hujjatlar qidiruv tizimi',
    summary: 'Lex.uz ochiq maʼlumotlar bazasi asosida yaratilgan zamonaviy va tezkor qidiruv xizmati.',
    url: 'https://t.me/it_loyihalar_uz/84',
    sourceType: 'telegram',
    sourceLabel: '@it_loyihalar_uz',
    collection: 'tools',
    tags: ['search', 'uzbek-language', 'api'],
    status: 'read',
    createdAt: '2026-09-13T16:00:00Z',
  },
  {
    id: 'sig-016',
    title: 'Staff Platform Engineer (Kubernetes / Go / AWS)',
    summary: 'High-scale infrastructure team looking for platform engineers with expertise in multi-region clusters and Terraform.',
    url: 'https://jobs.example.com/staff-platform',
    sourceType: 'web',
    sourceLabel: 'techcareers.io',
    collection: 'jobs',
    tags: ['devops', 'kubernetes', 'aws', 'golang'],
    status: 'new',
    createdAt: '2026-09-12T12:30:00Z',
  },
  {
    id: 'sig-017',
    title: 'Toshkent IT Park hududida rezidentlik shartlari',
    summary: 'IT Park rezidentlari uchun soliq imtiyozlari, eksport talablari va roʻyxatdan oʻtish bosqichlari tahlili.',
    url: 'https://it-park.uz/residents-guide',
    sourceType: 'web',
    sourceLabel: 'it-park.uz',
    collection: 'other',
    tags: ['it-park', 'soliq', 'biznes'],
    status: 'read',
    createdAt: '2026-09-12T09:15:00Z',
  },
  {
    id: 'sig-018',
    title: 'Modern CSS Layouts: Subgrid, Anchor Positioning & Container Queries',
    summary: 'Comprehensive workshop on emerging CSS layout features with production-ready polyfills and progressive enhancement.',
    url: 'https://ishadeed.com/article/css-subgrid-anchor',
    sourceType: 'web',
    sourceLabel: 'ishadeed.com',
    collection: 'courses',
    tags: ['css', 'layout', 'subgrid', 'web-standards'],
    status: 'done',
    createdAt: '2026-09-11T14:45:00Z',
  },
  {
    id: 'sig-019',
    title: 'Landing Page & Branding for SaaS Company (Uzbek/English)',
    summary: 'Create a clean, typography-focused marketing landing page with bilingual copy and SVG illustration assets.',
    url: 'https://freelance.example.com/task/940',
    sourceType: 'telegram',
    sourceLabel: '@freelance_tashkent',
    collection: 'freelance',
    tags: ['freelance', 'landing', 'bilingual', 'tailwind'],
    status: 'read',
    deadline: '2026-09-28',
    createdAt: '2026-09-11T10:00:00Z',
  },
  {
    id: 'sig-020',
    title: 'Zod vs ArkType vs Valibot: Runtime Schema Validation Benchmarks',
    summary: 'Performance comparison of leading TypeScript validation libraries focusing on bundle size impact and parsing speed.',
    url: 'https://valibot.dev/guides/comparison',
    sourceType: 'web',
    sourceLabel: 'valibot.dev',
    collection: 'tools',
    tags: ['typescript', 'validation', 'benchmarks', 'performance'],
    status: 'done',
    createdAt: '2026-09-10T18:25:00Z',
  },
  {
    id: 'sig-021',
    title: 'Mirzo Ulugʻbek tumanida sokin hovli ijarasi',
    summary: 'Katta bogʻli, yozgi ayvon va ish xonasi ajratilgan shinam hovli. Uzoq muddatga oilaga beriladi.',
    url: 'https://t.me/uyjoy_toshkent/1029',
    sourceType: 'telegram',
    sourceLabel: '@uyjoy_toshkent',
    collection: 'housing',
    tags: ['toshkent', 'hovli', 'ijara'],
    status: 'new',
    createdAt: '2026-09-10T11:40:00Z',
  },
  {
    id: 'sig-022',
    title: 'TypeScript 5.8: Granular Return Type Inference & Performance',
    summary: 'Detailed release notes covering conditional type optimizations, node_modules resolution improvements, and memory efficiency.',
    url: 'https://devblogs.microsoft.com/typescript/announcing-typescript-5-8',
    sourceType: 'web',
    sourceLabel: 'microsoft.com/typescript',
    collection: 'courses',
    tags: ['typescript', 'compiler', 'release-notes'],
    status: 'read',
    createdAt: '2026-09-09T16:10:00Z',
  },
  {
    id: 'sig-023',
    title: 'Senior Backend Engineer (Python / FastAPI / AsyncIO)',
    summary: 'Fast-growing analytics startup hiring backend developers to build real-time event streaming pipelines.',
    url: 'https://jobs.example.com/senior-python',
    sourceType: 'telegram',
    sourceLabel: '@python_jobs_central',
    collection: 'jobs',
    tags: ['python', 'fastapi', 'asyncio', 'kafka'],
    status: 'new',
    createdAt: '2026-09-09T08:55:00Z',
  },
  {
    id: 'sig-024',
    title: 'Docker va Docker Compose orqali mahalliy ishlab chiqish muhiti',
    summary: 'PostgreSQL, Redis va Mailpit kabi xizmatlarni bitta compose faylida sozlash va ishlab chiqish jarayonini tezlashtirish.',
    url: 'https://t.me/devops_uzbekistan/721',
    sourceType: 'telegram',
    sourceLabel: '@devops_uzbekistan',
    collection: 'tools',
    tags: ['docker', 'devops', 'postgres', 'local-dev'],
    status: 'done',
    createdAt: '2026-09-08T15:30:00Z',
  },
  {
    id: 'sig-025',
    title: 'Next.js App Router: Master Course on Caching & Invalidation',
    summary: 'Deep dive into full-route cache, request memoization, unstable_cache, and tag-based on-demand revalidation.',
    url: 'https://nextjs.org/docs/app/building-your-application/caching',
    sourceType: 'web',
    sourceLabel: 'nextjs.org',
    collection: 'courses',
    tags: ['nextjs', 'caching', 'server-components', 'web'],
    status: 'read',
    note: 'Important for understanding static vs dynamic route generation in Kepio.',
    createdAt: '2026-09-08T10:00:00Z',
  },
  {
    id: 'sig-026',
    title: 'Micro-consulting: Database Migration from MySQL to PostgreSQL',
    summary: 'Help a local fintech company migrate schemas, stored procedures, and 50GB dataset with minimal downtime.',
    url: 'https://freelance.example.com/consulting/89',
    sourceType: 'web',
    sourceLabel: 'consultinghub.io',
    collection: 'freelance',
    tags: ['freelance', 'postgres', 'mysql', 'migration'],
    status: 'new',
    deadline: '2026-09-27',
    createdAt: '2026-09-07T17:20:00Z',
  },
  {
    id: 'sig-027',
    title: 'Playwright E2E Testing with WCAG Accessibility Assertions',
    summary: 'Best practices for integrating @axe-core/playwright into CI pipelines to catch color contrast and ARIA defects automatically.',
    url: 'https://playwright.dev/docs/accessibility-testing',
    sourceType: 'web',
    sourceLabel: 'playwright.dev',
    collection: 'tools',
    tags: ['testing', 'playwright', 'a11y', 'ci-cd'],
    status: 'done',
    note: 'Reference for writing automated test suite in Phase 5.',
    createdAt: '2026-09-07T12:00:00Z',
  },
  {
    id: 'sig-028',
    title: 'Chilonzor metrosiga 5 daqiqalik 2 xonali kvartira',
    summary: 'Konditsioner, kir yuvish mashinasi va mebellari mavjud. Kommunal toʻlovlar alohida hisoblanadi.',
    url: 'https://t.me/chilonzor_ijara/33',
    sourceType: 'telegram',
    sourceLabel: '@chilonzor_ijara',
    collection: 'housing',
    tags: ['toshkent', 'ijara', 'chilonzor'],
    status: 'archived',
    createdAt: '2026-09-06T19:10:00Z',
  },
  {
    id: 'sig-029',
    title: 'Staff QA Automation Engineer (TypeScript & Playwright)',
    summary: 'Lead the automated testing strategy across microfrontends and mobile web viewports.',
    url: 'https://jobs.example.com/staff-qa',
    sourceType: 'web',
    sourceLabel: 'qualityengineers.co',
    collection: 'jobs',
    tags: ['qa', 'playwright', 'typescript', 'automation'],
    status: 'new',
    createdAt: '2026-09-06T14:40:00Z',
  },
  {
    id: 'sig-030',
    title: 'Shaxsiy moliya va daromadlarni hisobga olish jadvali (Notion/Excel)',
    summary: 'Oylik xarajatlar, jamgʻarma va investitsiyalarni kuzatish uchun qulay andoza.',
    url: 'https://t.me/foydali_manbalar_uz/99',
    sourceType: 'telegram',
    sourceLabel: '@foydali_manbalar_uz',
    collection: 'other',
    tags: ['moliya', 'notion', 'rejalashtirish'],
    status: 'read',
    createdAt: '2026-09-05T18:00:00Z',
  },
  {
    id: 'sig-031',
    title: 'Tailwind Merge: Intelligent Conflict Resolution for Dynamic Classes',
    summary: 'How tailwind-merge inspects utility class specificity and prevents unexpected override bugs in reusable React components.',
    url: 'https://github.com/dcastil/tailwind-merge',
    sourceType: 'web',
    sourceLabel: 'github.com/tailwind-merge',
    collection: 'tools',
    tags: ['tailwind', 'css', 'react', 'utilities'],
    status: 'done',
    createdAt: '2026-09-05T11:15:00Z',
  },
  {
    id: 'sig-032',
    title: 'Vue 3 to React Migration Consultancy',
    summary: 'Assist a client with architecture review and code migration strategies for a dashboard application with 40+ views.',
    url: 'https://freelance.example.com/migration-contract',
    sourceType: 'web',
    sourceLabel: 'freelancenet.io',
    collection: 'freelance',
    tags: ['freelance', 'react', 'vue', 'migration'],
    status: 'read',
    deadline: '2026-10-01',
    createdAt: '2026-09-04T16:50:00Z',
  },
  {
    id: 'sig-033',
    title: 'Kiberxavfsizlik asoslari va tarmoq auditi amaliyoti',
    summary: 'OWASP Top 10 zaifliklari, SQL inʼyeksiya, XSS va CSRF xurujlaridan himoyalanish boʻyicha oʻzbekcha video darslar turkumi.',
    url: 'https://t.me/cybersecurity_uz/401',
    sourceType: 'telegram',
    sourceLabel: '@cybersecurity_uz',
    collection: 'courses',
    tags: ['security', 'owasp', 'web-security'],
    status: 'new',
    createdAt: '2026-09-04T09:30:00Z',
  },
  {
    id: 'sig-034',
    title: 'Engineering Manager (Core Infrastructure / Remote)',
    summary: 'Leading a distributed team of 8 senior infrastructure engineers focusing on reliability, SLOs, and incident response.',
    url: 'https://jobs.example.com/em-infrastructure',
    sourceType: 'web',
    sourceLabel: 'leadershipjobs.org',
    collection: 'jobs',
    tags: ['engineering-management', 'leadership', 'remote'],
    status: 'archived',
    createdAt: '2026-09-03T17:40:00Z',
  },
  {
    id: 'sig-035',
    title: 'Yakkasaroyda ofis binosi va shourum ijarasi',
    summary: 'Asosiy yoʻl yoqasida joylashgan 120 kv.m maydonga ega zamonaviy ofis xonalari.',
    url: 'https://t.me/tashkent_realestate/882',
    sourceType: 'telegram',
    sourceLabel: '@tashkent_realestate',
    collection: 'housing',
    tags: ['toshkent', 'ofis', 'yakkasaroy'],
    status: 'read',
    createdAt: '2026-09-03T13:00:00Z',
  },
  {
    id: 'sig-036',
    title: 'HTTP/3 and QUIC Protocol Internals for Web Performance',
    summary: 'Detailed explanation of zero-RTT connection establishment, head-of-line blocking elimination, and UDP transport mechanics.',
    url: 'https://cloudflare.com/learning/performance/what-is-http3',
    sourceType: 'web',
    sourceLabel: 'cloudflare.com',
    collection: 'courses',
    tags: ['http3', 'networking', 'performance', 'quic'],
    status: 'done',
    createdAt: '2026-09-02T15:20:00Z',
  },
  {
    id: 'sig-037',
    title: 'Web Scraping & Data Pipeline using Playwright + DuckDB',
    summary: 'Building automated data collectors that extract structured price indexes and store them in lightweight columnar format.',
    url: 'https://github.com/example/playwright-duckdb-pipeline',
    sourceType: 'web',
    sourceLabel: 'github.com/data-craft',
    collection: 'tools',
    tags: ['playwright', 'duckdb', 'data-pipeline', 'scraping'],
    status: 'new',
    createdAt: '2026-09-02T10:10:00Z',
  },
  {
    id: 'sig-038',
    title: 'Toshkentda kitobsevarlar klubi va muhokama kechalari',
    summary: 'Har shanba kuni badiiy va ilmiy-ommabop kitoblar tahlili, fikr almashish va muloqot maydoni.',
    url: 'https://t.me/kitobxonlar_klubi/12',
    sourceType: 'telegram',
    sourceLabel: '@kitobxonlar_klubi',
    collection: 'other',
    tags: ['kitob', 'toshkent', 'muloqot'],
    status: 'done',
    createdAt: '2026-09-01T19:00:00Z',
  },
  {
    id: 'sig-039',
    title: 'React Native Developer for Health & Fitness Application',
    summary: 'Build Bluetooth integration module for smart fitness trackers with offline workout sync capabilities.',
    url: 'https://freelance.example.com/mobile-fitness',
    sourceType: 'telegram',
    sourceLabel: '@mobile_dev_freelance',
    collection: 'freelance',
    tags: ['freelance', 'react-native', 'bluetooth', 'mobile'],
    status: 'new',
    deadline: '2026-09-30',
    createdAt: '2026-09-01T14:15:00Z',
  },
  {
    id: 'sig-040',
    title: 'Principal Database Architect (PostgreSQL internals / Remote)',
    summary: 'Design high-throughput distributed database clustering and replication topology for billions of daily transactions.',
    url: 'https://jobs.example.com/principal-db-architect',
    sourceType: 'web',
    sourceLabel: 'remotetechjobs.io',
    collection: 'jobs',
    tags: ['postgres', 'architecture', 'remote', 'principal'],
    status: 'read',
    createdAt: '2026-08-31T11:45:00Z',
  },
  {
    id: 'sig-041',
    title: 'SVG Optimizations and Paper UI Texture Synthesis',
    summary: 'How to generate sub-2KB inline SVG fractal noise patterns to create physical paper grain effects without external image assets.',
    url: 'https://css-tricks.com/creating-paper-textures-with-svg-filters',
    sourceType: 'web',
    sourceLabel: 'css-tricks.com',
    collection: 'tools',
    tags: ['svg', 'paper-ui', 'design', 'performance'],
    status: 'done',
    note: 'Directly applied to Kepio globals.css SVG noise overlay.',
    createdAt: '2026-08-30T16:00:00Z',
  },
  {
    id: 'sig-042',
    title: 'Zamonaviy Oʻzbekiston arxitekturasi va shaharsozlik koʻrgazmasi',
    summary: 'Toshkent shahar tarixi muzeyida boʻlib oʻtadigan shaharsozlik va landshaft dizayni boʻyicha ochiq koʻrgazma.',
    url: 'https://t.me/tashkent_culture/514',
    sourceType: 'telegram',
    sourceLabel: '@tashkent_culture',
    collection: 'other',
    tags: ['toshkent', 'madaniyat', 'arxitektura'],
    status: 'archived',
    createdAt: '2026-08-30T10:20:00Z',
  },
];
