import { Dictionary } from './types';

export const en: Dictionary = {
  locale: 'en',
  brand: {
    name: 'KEPIO',
    tagline: 'Personal notebook for knowledge and findings',
    subtagline: 'Find → Keep → Act',
  },
  a11y: {
    skipLink: 'Skip to main content',
    mainNavigation: 'Main navigation',
    languageSelector: 'Choose language',
    userProfile: 'User profile',
    reducedDecorToggle: 'Toggle reduced decoration',
    errorSummary: 'Form error summary',
    statusRadioGroup: 'Change signal status',
    pagination: 'Pagination',
  },
  nav: {
    library: 'Library',
    daily: 'Daily',
    archive: 'Archive',
    settings: 'Settings',
    signIn: 'Sign in',
    signOut: 'Sign out',
  },
  stamps: {
    header: 'PERSONAL NOTES',
    new: 'NEW',
    read: 'READ',
    done: 'DONE',
    archived: 'ARCHIVED',
  },
  collections: {
    all: 'All',
    jobs: 'Jobs',
    freelance: 'Freelance',
    courses: 'Courses',
    housing: 'Housing',
    tools: 'Tools',
    other: 'Other',
    newCollectionDisabled: '+ New collection',
  },
  sort: {
    label: 'Sort',
    recent: 'Recently added',
    oldest: 'Oldest added',
    title: 'By title (A-Z)',
  },
  landing: {
    eyebrow: 'KEPIO / KEE-pee-oh · keep it',
    h1Part1: 'You found something useful. ',
    h1Accent: "Now don't lose it.",
    subtitle: 'Save and organize the best opportunities, jobs, courses, and tools you discover across Telegram and the web.',
    primaryCta: 'Start keeping →',
    secondaryLink: 'How it works',
    stepsTitle: 'A simple three-step workflow',
    steps: {
      find: {
        title: '01 · Find',
        desc: 'Grab a link or snippet from Telegram channels, communities, or web pages you read.',
      },
      keep: {
        title: '02 · Keep',
        desc: 'Seal it into your notebook with a single tap. Tag, organize into collections, and write a quick summary.',
      },
      act: {
        title: '03 · Act',
        desc: "Don't let it sit forgotten. Set deadlines, mark progress, and follow through.",
      },
    },
    quote: '“Leave the remembering to us. Your job is to act.”',
    microClaims: 'Uzbek & English · No ads',
    finalCtaTitle: 'Seal your knowledge into paper',
    finalCtaSubtitle: 'A quiet, tactile workspace designed for focus and execution.',
    telegramBot: 'Telegram bot · Coming soon',
    chromeExtension: 'Chrome extension · Coming soon',
  },
  library: {
    title: 'Library',
    searchPlaceholder: 'Search by title, tag, source...',
    searchShortcutHint: 'Ctrl+K',
    fromTheMargin: 'From the margin',
    statsTitle: 'Library overview',
    statsTotal: 'Total saved',
    statsActive: 'Active items',
    statsCompleted: 'Completed',
    emptyTitle: 'No entries found',
    emptyDesc: 'No saved items match your current filter or search query.',
    emptyReset: 'Reset all filters',
    addSignalCta: 'Add new entry',
    viewOriginal: 'View source',
    nextStepTitle: 'Next step',
    deadlineLabel: 'Deadline',
    noDeadline: 'No deadline set',
    statusChangeSuccess: 'Status updated successfully',
    backToLibrary: '← Back to library',
  },
  forms: {
    newSignalTitle: 'Keep a new entry',
    newSignalSubtitle: 'Seal a finding from Telegram or the web into your notebook',
    urlOrTextLabel: 'URL or primary content',
    urlOrTextPlaceholder: 'https://t.me/... or https://example.com/...',
    titleLabel: 'Title',
    titlePlaceholder: 'e.g. Senior Frontend Engineer vacancy',
    summaryLabel: 'Summary / Key takeaways',
    summaryPlaceholder: 'The most important aspects of this finding...',
    sourceTypeLabel: 'Source type',
    sourceTelegram: 'Telegram',
    sourceWeb: 'Web',
    sourceOther: 'Other',
    sourceChannelLabel: 'Channel or site name',
    sourceChannelPlaceholder: 'e.g. @dev_jobs_channel or github.com',
    collectionLabel: 'Collection',
    tagsLabel: 'Tags',
    tagsPlaceholder: 'Type a tag and press Enter...',
    tagsHint: 'Separate with comma or press Enter',
    noteLabel: 'Personal memo / next action',
    notePlaceholder: 'e.g. Update resume and submit proposal by Friday',
    deadlineLabel: 'Due date (optional)',
    submitButton: 'Seal to notebook →',
    submitting: 'Sealing...',
    cancelButton: 'Cancel',
    successToast: 'Entry sealed successfully!',
    errors: {
      titleRequired: 'Title is required (at least 3 characters)',
      urlInvalid: 'Please enter a valid URL (https://...)',
      collectionRequired: 'Please select a collection',
    },
  },
  daily: {
    title: 'Daily register',
    subtitle: "Today's saved items, quick memos, and actionable checklist",
    stamp: 'DAILY REGISTER',
    quickEntryTitle: 'Quick entry',
    quickEntryPlaceholder: 'Type a quick link or note...',
    quickEntryButton: 'Add entry',
    tableCaption: 'Daily register entries and saved references',
    colDate: 'Date',
    colSource: 'Source',
    colContent: 'Title & Summary',
    colStatus: 'Status',
    colActions: 'Actions',
    memoTitle: 'Daily memo',
    memoContent: 'Focus on at most 3 core priorities each day. Consistency beats intensity.',
    actionsTitle: 'Actions',
    exportCsv: 'Export table as CSV',
    printSheet: 'Print sheet',
    closeDayButton: 'Close the day',
    progressTitle: 'Daily progress',
    progressSummary: 'Reviewed 5 out of 8 items captured today.',
    emptyDaily: 'No entries captured today yet.',
  },
  signIn: {
    title: 'Sign in to Kepio',
    tabSignIn: 'Sign in',
    tabSignUp: 'Create account',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    nameLabel: 'Full name',
    namePlaceholder: 'Alex Mercer',
    showPassword: 'Show',
    hidePassword: 'Hide',
    submitSignIn: 'Sign in →',
    submitSignUp: 'Create account →',
    mockHint: 'Demo mode: enter any email and password to sign in immediately.',
  },
  archive: {
    title: 'Archive',
    subtitle: 'Completed tasks and archived knowledge kept for historical reference',
    emptyTitle: 'Archive is empty',
    emptyDesc: 'Items marked as completed or archived will appear here.',
    restoreButton: 'Restore to library',
  },
  settings: {
    title: 'Settings',
    subtitle: 'Manage visual appearance and preferences for your notebook',
    appearanceSection: 'Visual appearance & theme',
    reducedDecorLabel: 'Reduced decoration',
    reducedDecorDesc: 'Disable paper textures, rotation, and heavy shadows for a flat, high-contrast look.',
    languageSection: 'Interface language',
    languageDesc: 'Choose your preferred language for the application interface.',
    dataSection: 'Data management',
    dataDesc: 'Reset or manage your local in-memory mock notebook data.',
    resetDemoData: 'Reset demo data to default',
    resetDone: 'Data reset successfully',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    comingSoon: 'Coming soon',
    searchPlaceholder: 'Search...',
    searchShortcutHint: 'Ctrl+K',
    page: 'Page',
    of: 'of',
    total: 'total',
    loading: 'Loading...',
    allFilter: 'All',
    statusAll: 'All statuses',
  },
  footer: {
    description: 'A tactile personal notebook for saving, organizing, and acting on findings from Telegram and the web.',
    specsLink: 'Design System (Specs)',
    decorToggleActive: 'Decor: Off',
    decorToggleDefault: 'Decor: On',
    rights: 'All rights reserved.',
  },
};
