import { Dictionary } from './types';

export const uz: Dictionary = {
  locale: 'uz',
  brand: {
    name: 'KEPIO',
    tagline: 'Shaxsiy bilimlar va eslatmalar daftari',
    subtagline: 'Top → Saqla → Bajar',
  },
  a11y: {
    skipLink: 'Asosiy kontentga oʻtish',
    mainNavigation: 'Asosiy navigatsiya',
    languageSelector: 'Tilni tanlash',
    userProfile: 'Foydalanuvchi profili',
    reducedDecorToggle: 'Bezaklarni kamaytirish rejimi',
    errorSummary: 'Formadagi xatoliklar roʻyxati',
    statusRadioGroup: 'Qayd holatini oʻzgartirish',
    pagination: 'Sahifalar',
  },
  nav: {
    library: 'Kutubxona',
    daily: 'Kun tartibi',
    archive: 'Arxiv',
    settings: 'Sozlamalar',
    signIn: 'Kirish',
    signOut: 'Chiqish',
  },
  stamps: {
    header: 'SHAXSIY BILIMLAR',
    new: 'YANGI',
    read: 'OʻQILDI',
    done: 'BAJARILDI',
    archived: 'ARXIVLANDI',
  },
  collections: {
    all: 'Barchasi',
    jobs: 'Ish',
    freelance: 'Freelance',
    courses: 'Kurslar',
    housing: 'Uy-joy',
    tools: 'Asboblar',
    other: 'Boshqa',
    newCollectionDisabled: '+ Yangi toifa',
  },
  sort: {
    label: 'Saralash',
    recent: 'Yangi qoʻshilganlar',
    oldest: 'Avval qoʻshilganlar',
    title: 'Sarlavha boʻyicha (A-Z)',
  },
  landing: {
    eyebrow: 'KEPIO / KEE-pee-oh · keep it',
    h1Part1: 'Foydali narsani topding. ',
    h1Accent: 'Endi yoʻqotma.',
    subtitle: 'Telegram va internetda uchragan eng muhim bilimlarni, vakansiyalarni va vositalarni bitta tartibli joyda jamlang.',
    primaryCta: 'Saqlashni boshlash →',
    secondaryLink: 'Qanday ishlaydi',
    stepsTitle: 'Oddiy uch qadamli jarayon',
    steps: {
      find: {
        title: '01 · Top',
        desc: 'Telegram kanallari yoki veb-saytlarda koʻrgan foydali resursingiz havolasini yoki matnini oling.',
      },
      keep: {
        title: '02 · Saqla',
        desc: 'Birgina harakat bilan daftaringizga muhrlang. Kerakli toifa, teglar va qisqa xulosani belgilang.',
      },
      act: {
        title: '03 · Bajar',
        desc: 'Shunchaki saqlab qoʻymang. Muddat belgilang, holatini yangilang va natijaga erishing.',
      },
    },
    quote: '“Eslab qolishni bizga qoldir. Sening ishing — bajarish.”',
    microClaims: 'Oʻzbekcha va inglizcha · Reklamasiz',
    finalCtaTitle: 'Foydali bilimlarni qogʻozga muhrlang',
    finalCtaSubtitle: 'Hech qanday keraksiz murakkabliksiz, qulay va yengil daftaringiz.',
    telegramBot: 'Telegram bot · Tez orada',
    chromeExtension: 'Chrome kengaytmasi · Tez orada',
  },
  library: {
    title: 'Kutubxona',
    searchPlaceholder: 'Qidirish (sarlavha, teg, manba)...',
    searchShortcutHint: 'Ctrl+K',
    fromTheMargin: 'Hoshiyadan',
    statsTitle: 'Kutubxona hisoboti',
    statsTotal: 'Jami saqlanganlar',
    statsActive: 'Faol vazifalar',
    statsCompleted: 'Yakunlanganlar',
    emptyTitle: 'Hozircha hech narsa topilmadi',
    emptyDesc: 'Tanlangan filtrlar yoki qidiruv soʻrovi boʻyicha hech qanday qayd mavjud emas.',
    emptyReset: 'Barcha filtrlarni tozalash',
    addSignalCta: 'Yangi qayd qoʻshish',
    viewOriginal: 'Asl manbani ochish',
    nextStepTitle: 'Keyingi qadam',
    deadlineLabel: 'Muddati',
    noDeadline: 'Muddat belgilanmagan',
    statusChangeSuccess: 'Holat muvaffaqiyatli yangilandi',
    backToLibrary: '← Kutubxonaga qaytish',
  },
  forms: {
    newSignalTitle: 'Yangi qayd kiritish',
    newSignalSubtitle: 'Internet yoki Telegramdan topilgan manbani daftarga muhrlash',
    urlOrTextLabel: 'Havola (URL) yoki asosiy matn',
    urlOrTextPlaceholder: 'https://t.me/... yoki https://example.com/...',
    titleLabel: 'Sarlavha',
    titlePlaceholder: 'Masalan: Senior Frontend Engineer vakansiyasi',
    summaryLabel: 'Qisqa tavsif / xulosa',
    summaryPlaceholder: 'Ushbu manbaning eng muhim jihatlari...',
    sourceTypeLabel: 'Manba turi',
    sourceTelegram: 'Telegram',
    sourceWeb: 'Veb-sayt',
    sourceOther: 'Boshqa',
    sourceChannelLabel: 'Kanal yoki sayt nomi',
    sourceChannelPlaceholder: 'Masalan: @dev_jobs_uz yoki github.com',
    collectionLabel: 'Toifa',
    tagsLabel: 'Teglar',
    tagsPlaceholder: 'Teg yozing va Enter bosing...',
    tagsHint: 'Vergul yoki Enter orqali ajrating',
    noteLabel: 'Shaxsiy eslatma / keyingi harakat',
    notePlaceholder: 'Masalan: Juma kuniga qadar rezyume yuborish lozim',
    deadlineLabel: 'Bajarish muddati (ixtiyoriy)',
    submitButton: 'Daftarga muhrlash →',
    submitting: 'Saqlanmoqda...',
    cancelButton: 'Bekor qilish',
    successToast: 'Qayd muvaffaqiyatli saqlandi!',
    errors: {
      titleRequired: 'Sarlavhani kiritish majburiy (kamida 3 ta belgi)',
      urlInvalid: 'Iltimos, toʻgʻri internet manzilini kiriting (https://...)',
      collectionRequired: 'Iltimos, toifani tanlang',
    },
  },
  daily: {
    title: 'Kun tartibi',
    subtitle: 'Bugun saqlangan muhim resurslar va bajarilishi kerak boʻlgan ishlar roʻyxati',
    stamp: 'KUN TARTIBI',
    quickEntryTitle: 'Tezkor qayd kiritish',
    quickEntryPlaceholder: 'Tezkor havola yoki eslatma yozing...',
    quickEntryButton: 'Qoʻshish',
    tableCaption: 'Kunlik qaydlar va saqlangan materiallar jadvali',
    colDate: 'Sana',
    colSource: 'Manba',
    colContent: 'Sarlavha va mazmun',
    colStatus: 'Holat',
    colActions: 'Amallar',
    memoTitle: 'Kunlik xotira',
    memoContent: 'Har kuni 3 tadan koʻp boʻlmagan ustuvor vazifaga diqqatni jamlang. Tartib intizomni yengadi.',
    actionsTitle: 'Amallar',
    exportCsv: 'Jadvalni CSV yuklash',
    printSheet: 'Varaqni chop etish',
    closeDayButton: 'Kuni yakunlash',
    progressTitle: 'Kunlik unumdorlik',
    progressSummary: 'Bugungi 8 ta muhim qayddan 5 tasi koʻrib chiqildi.',
    emptyDaily: 'Bugun hali hech qanday qayd kiritilmadi.',
  },
  signIn: {
    title: 'Kepio hisobiga kirish',
    tabSignIn: 'Kirish',
    tabSignUp: 'Roʻyxatdan oʻtish',
    emailLabel: 'Elektron pochta',
    emailPlaceholder: 'ismingiz@misol.uz',
    passwordLabel: 'Parol',
    passwordPlaceholder: '••••••••',
    nameLabel: 'Toʻliq ismingiz',
    namePlaceholder: 'Anvar Qodirov',
    showPassword: 'Koʻrsatish',
    hidePassword: 'Yashirish',
    submitSignIn: 'Hisobga kirish →',
    submitSignUp: 'Roʻyxatdan oʻtish →',
    mockHint: 'Demo rejim: ixtiyoriy elektron pochta va parol bilan toʻgʻridan-toʻgʻri kirishingiz mumkin.',
  },
  archive: {
    title: 'Arxiv',
    subtitle: 'Oldin bajarilgan yoki arxivga oʻtkazilgan barcha bilimlar va qaydlar toʻplami',
    emptyTitle: 'Arxivda hech narsa yoʻq',
    emptyDesc: 'Bajarilgan va arxivlangan maʼlumotlar shu yerda saqlanadi.',
    restoreButton: 'Kutubxonaga qaytarish',
  },
  settings: {
    title: 'Sozlamalar',
    subtitle: 'Kepio shaxsiy daftaringizning tashqi koʻrinishi va parametrlarini boshqaring',
    appearanceSection: 'Tashqi koʻrinish va mavzu',
    reducedDecorLabel: 'Bezaklarni kamaytirish (Reduced decoration)',
    reducedDecorDesc: 'Qogʻoz teksturasi va ortiqcha soyalarni oʻchirib, toza yassi dizaynga oʻtish.',
    languageSection: 'Interfeys tili',
    languageDesc: 'Ilovadan foydalanish uchun qulay tilni tanlang.',
    dataSection: 'Maʼlumotlar ombori',
    dataDesc: 'Mahalliy mock maʼlumotlarni boshqarish yoki boshlangʻich holatga qaytarish.',
    resetDemoData: 'Demo maʼlumotlarni qayta tiklash',
    resetDone: 'Maʼlumotlar muvaffaqiyatli tiklandi',
  },
  common: {
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    comingSoon: 'Tez orada',
    searchPlaceholder: 'Qidirish...',
    searchShortcutHint: 'Ctrl+K',
    page: 'Varaq',
    of: '/',
    total: 'Jami',
    loading: 'Yuklanmoqda...',
    allFilter: 'Barchasi',
    statusAll: 'Barcha holatlar',
  },
  footer: {
    description: 'Telegram va internetdagi eng muhim maʼlumotlarni saqlash va boshqarish uchun shaxsiy daftarcha.',
    specsLink: 'Dizayn tizimi (Specs)',
    decorToggleActive: 'Bezaklar: Oʻchiq',
    decorToggleDefault: 'Bezaklar: Yoniq',
    rights: 'Barcha huquqlar himoyalangan.',
  },
};
